In [1]:
# To enable plotting graphs in Jupyter notebook. 
# This should always be the first step before importing the other libraries
%matplotlib inline

In [61]:
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
import seaborn as sns
from imblearn.over_sampling import SMOTE

In [62]:
import os
os.chdir('C:/Users/ASHISH/Desktop/CLASSIFICATION-SUPERVISED LEARNING')

In [63]:
data1 = pd.read_csv("train_1.csv")
data2 = pd.read_csv("train_2.csv")
data3 = pd.read_csv('test.csv')

In [93]:
merged_data= pd.merge(data1, data2)

In [94]:
merged_data

Ref.No      X1  X2  X3  X4  X5  X6  X7  Y  X8  X9  X10  X11     X12  \
0       22203  320000   2   1   2  27   1   2  1   2   2    2    2   43243   
1        1288  470000   1   2   1  41  -2  -2  0  -2  -2   -2   -1   13780   
2       11822   20000   1   2   2  25   1   2  0   0   0    0    0   20415   
3       15085   80000   1   3   1  41   0   0  1   0   0    0   -1   76015   
4        6192   30000   1   1   2  30   1  -2  1  -2  -2   -2   -2       0   
5       12894  320000   2   2   1  39   0   0  0   0   0    0    0  147440   
6        2279   50000   2   3   1  37   2   0  1   0   0    0    0   38527   
7        1282  360000   1   1   2  34   1  -2  0  -2  -2   -2   -1       0   
8       13334   50000   2   1   1  25   0   0  0   0   0    2    0   11324   
9       15251   30000   2   2   1  45   2   0  0   0   0    0    0   31548   
10      12165  130000   2   3   1  41   0   0  0   0   0    0    0  131728   
11       9895  270000   2   2   1  42   0   0  0   0   0    0    0  225245   
12      18930  200000   2   1   1  30  -2  -2  0  -2  -2   -2   -2    4833   
13      16828  150000   1   1   1  43  -2  -2  0  -2  -2   -1   -1    1000   
14      16492   50000   1   2   2  22   0   0  0   2   0    0    0   51083   
15       3785   30000   1   1   2  32   0   0  0   2   0    0    0   29250   
16      14665   30000   2   2   2  23   0   0  0   0   0    0    0   12775   
17      18146  260000   1   2   2  31   0   0  0   0   0    0    0    3113   
18       4376   60000   1   3   1  31   1   2  1   0   0    0    0   69311   
19      17544   20000   2   2   1  40   0   0  0   0   0   -1   -1   10470   
20      18421   40000   2   2   2  24   2   0  1   0   0    0    0   19012   
21      23940   50000   1   2   2  27   1   2  1   0   0    0    0   47568   
22       1273  370000   2   1   1  53  -1  -1  0  -1  -1   -1    0   21160   
23       4811  300000   2   1   2  31   0   0  0  -1  -1    0    0   60700   
24       8334  360000   1   1   1  44   0   0  0   0   0    0    0  333549   
25      15711  270000   1   1   1  45   1  -1  0  -1  -1   -1   -1       0   
26      16811  140000   1   3   1  38   0   0  0   0   0    0    0  138329   
27      13816  130000   1   1   2  43   0   0  0   0   0    0    0  130874   
28      20565   50000   1   3   2  25   0   0  0   0   0    0    0   35227   
29       9594   20000   2   1   2  26   2   2  1   2   2    2    2     300   
...       ...     ...  ..  ..  ..  ..  ..  .. ..  ..  ..  ...  ...     ...   
21570   20745  450000   1   1   1  45  -1  -1  1  -1   0    0    0   26773   
21571    4885   70000   1   2   2  30   0   0  1   2   2    2    2   17526   
21572    7208  200000   2   2   1  44  -1   2  0  -1  -1    0    0     500   
21573   17977  120000   1   2   1  45   0   0  0   0   0    0    0   52574   
21574   19881  200000   2   2   2  36   0   0  1   0   0    0    0    9738   
21575   19480   50000   2   3   2  35   0   0  0  -1   0   -1    0   54731   
21576   12381  210000   2   1   2  27   0   0  0   0   0    0   -1   99050   
21577    2342  140000   2   3   2  33   1  -2  0  -2  -1   -1   -1       0   
21578   12838  150000   2   2   2  23   0   0  0   0   0    0    0  115206   
21579   18953   70000   2   1   2  26   0   0  0   0   0    0    0   64471   
21580   14238  500000   1   1   2  41  -1  -1  1  -1   0    0   -1     326   
21581    7306   50000   1   2   3  51   0   0  0   0   0    0    0   79502   
21582   11652  130000   2   1   2  30   1  -2  0  -2  -2   -2   -2    -915   
21583    3637   50000   1   3   2  30   0   0  0   0   0    2    0    6615   
21584    2308   30000   2   1   2  30   1  -2  0  -1  -1   -1   -1       0   
21585    3224   30000   2   2   2  28  -1  -1  1  -2  -1   -1   -2    1743   
21586   22787  100000   2   3   1  40   2   2  1   0   0    0    0   13278   
21587   17130   80000   2   2   2  24   2   2  1   2   2    2    2   22453   
21588    4029   60000   2   2   2  27   0   0  0   0   0    0    0   18224   
21589   23408  360000   2   2

In [66]:
merged_data.shape

(21600, 17)

In [67]:
merged_data_feature = merged_data.drop(labels= "Y" , axis = 1)


In [68]:
merged_data_feature

Ref.No      X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  X11     X12  \
0       22203  320000   2   1   2  27   1   2   2   2    2    2   43243   
1        1288  470000   1   2   1  41  -2  -2  -2  -2   -2   -1   13780   
2       11822   20000   1   2   2  25   1   2   0   0    0    0   20415   
3       15085   80000   1   3   1  41   0   0   0   0    0   -1   76015   
4        6192   30000   1   1   2  30   1  -2  -2  -2   -2   -2       0   
5       12894  320000   2   2   1  39   0   0   0   0    0    0  147440   
6        2279   50000   2   3   1  37   2   0   0   0    0    0   38527   
7        1282  360000   1   1   2  34   1  -2  -2  -2   -2   -1       0   
8       13334   50000   2   1   1  25   0   0   0   0    2    0   11324   
9       15251   30000   2   2   1  45   2   0   0   0    0    0   31548   
10      12165  130000   2   3   1  41   0   0   0   0    0    0  131728   
11       9895  270000   2   2   1  42   0   0   0   0    0    0  225245   
12      18930  200000   2   1   1  30  -2  -2  -2  -2   -2   -2    4833   
13      16828  150000   1   1   1  43  -2  -2  -2  -2   -1   -1    1000   
14      16492   50000   1   2   2  22   0   0   2   0    0    0   51083   
15       3785   30000   1   1   2  32   0   0   2   0    0    0   29250   
16      14665   30000   2   2   2  23   0   0   0   0    0    0   12775   
17      18146  260000   1   2   2  31   0   0   0   0    0    0    3113   
18       4376   60000   1   3   1  31   1   2   0   0    0    0   69311   
19      17544   20000   2   2   1  40   0   0   0   0   -1   -1   10470   
20      18421   40000   2   2   2  24   2   0   0   0    0    0   19012   
21      23940   50000   1   2   2  27   1   2   0   0    0    0   47568   
22       1273  370000   2   1   1  53  -1  -1  -1  -1   -1    0   21160   
23       4811  300000   2   1   2  31   0   0  -1  -1    0    0   60700   
24       8334  360000   1   1   1  44   0   0   0   0    0    0  333549   
25      15711  270000   1   1   1  45   1  -1  -1  -1   -1   -1       0   
26      16811  140000   1   3   1  38   0   0   0   0    0    0  138329   
27      13816  130000   1   1   2  43   0   0   0   0    0    0  130874   
28      20565   50000   1   3   2  25   0   0   0   0    0    0   35227   
29       9594   20000   2   1   2  26   2   2   2   2    2    2     300   
...       ...     ...  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...     ...   
21570   20745  450000   1   1   1  45  -1  -1  -1   0    0    0   26773   
21571    4885   70000   1   2   2  30   0   0   2   2    2    2   17526   
21572    7208  200000   2   2   1  44  -1   2  -1  -1    0    0     500   
21573   17977  120000   1   2   1  45   0   0   0   0    0    0   52574   
21574   19881  200000   2   2   2  36   0   0   0   0    0    0    9738   
21575   19480   50000   2   3   2  35   0   0  -1   0   -1    0   54731   
21576   12381  210000   2   1   2  27   0   0   0   0    0   -1   99050   
21577    2342  140000   2   3   2  33   1  -2  -2  -1   -1   -1       0   
21578   12838  150000   2   2   2  23   0   0   0   0    0    0  115206   
21579   18953   70000   2   1   2  26   0   0   0   0    0    0   64471   
21580   14238  500000   1   1   2  41  -1  -1  -1   0    0   -1     326   
21581    7306   50000   1   2   3  51   0   0   0   0    0    0   79502   
21582   11652  130000   2   1   2  30   1  -2  -2  -2   -2   -2    -915   
21583    3637   50000   1   3   2  30   0   0   0   0    2    0    6615   
21584    2308   30000   2   1   2  30   1  -2  -1  -1   -1   -1       0   
21585    3224   30000   2   2   2  28  -1  -1  -2  -1   -1   -2    1743   
21586   22787  100000   2   3   1  40   2   2   0   0    0    0   13278   
21587   17130   80000   2   2   2  24   2   2   2   2    2    2   22453   
21588    4029   60000   2   2   2  27   0   0   0   0    0    0   18224   
21589   23408  360000   2   2   2  35   1  -2  -1  -1    0   -1       0   
21590    4380  210000   2   1   1  42   1  -2  -2  -2   -2   -2       0   
21591   18482   50000   2   1   

In [69]:
data_test = data3.iloc[:,8:15].values

In [70]:
data_test

array([[    0,     0,     0, ..., 45342, 44719, 40002],
       [    0,     0,     0, ..., 11296, 12200, 11761],
       [   -1,    -1,    -2, ...,     0,     0,  2382],
       ...,
       [    2,     0,     0, ..., 40994, 43594, 38222],
       [    2,     2,     0, ...,  3902,  4686,  5459],
       [    0,     0,     0, ..., 20706, 21410, 22437]], dtype=int64)

In [71]:
merged_data_feature_z = merged_data_feature.apply(zscore) 

In [72]:
merged_data_feature_z

Ref.No        X1        X2        X3        X4        X5        X6  \
0      1.471889  1.199622  0.771310 -1.082964  0.845402 -0.904582  0.890581   
1     -1.545547  2.362316 -1.296495  0.197247 -1.070322  0.606227 -1.773392   
2     -0.025792 -1.125765 -1.296495  0.197247  0.845402 -1.120412  0.890581   
3      0.444966 -0.660688 -1.296495  1.477459 -1.070322  0.606227  0.002590   
4     -0.838040 -1.048252 -1.296495 -1.082964  0.845402 -0.580837  0.890581   
5      0.128867  1.199622  0.771310  0.197247 -1.070322  0.390397  0.002590   
6     -1.402574 -0.893226  0.771310  1.477459 -1.070322  0.174567  1.778572   
7     -1.546412  1.509674 -1.296495 -1.082964  0.845402 -0.149177  0.890581   
8      0.192346 -0.893226  0.771310 -1.082964 -1.070322 -1.120412  0.002590   
9      0.468915 -1.048252  0.771310  0.197247 -1.070322  1.037887  1.778572   
10     0.023693 -0.273123  0.771310  1.477459 -1.070322  0.606227  0.002590   
11    -0.303803  0.812058  0.771310  0.197247 -1.070322  0.714142  0.002590   
12     0.999689  0.269467  0.771310 -1.082964 -1.070322 -0.580837 -1.773392   
13     0.696431 -0.118097 -1.296495 -1.082964 -1.070322  0.822057 -1.773392   
14     0.647955 -0.893226 -1.296495  0.197247  0.845402 -1.444157  0.002590   
15    -1.185301 -1.048252 -1.296495 -1.082964  0.845402 -0.365007  0.002590   
16     0.384372 -1.048252  0.771310  0.197247  0.845402 -1.336242  0.002590   
17     0.886580  0.734545 -1.296495  0.197247  0.845402 -0.472922  0.002590   
18    -1.100037 -0.815713 -1.296495  1.477459 -1.070322 -0.472922  0.890581   
19     0.799729 -1.125765  0.771310  0.197247 -1.070322  0.498312  0.002590   
20     0.926255 -0.970739  0.771310  0.197247  0.845402 -1.228327  1.778572   
21     1.722489 -0.893226 -1.296495  0.197247  0.845402 -0.904582  0.890581   
22    -1.547711  1.587187  0.771310 -1.082964 -1.070322  1.901207 -0.885401   
23    -1.037279  1.044596  0.771310 -1.082964  0.845402 -0.472922  0.002590   
24    -0.529011  1.509674 -1.296495 -1.082964 -1.070322  0.929972  0.002590   
25     0.535280  0.812058 -1.296495 -1.082964 -1.070322  1.037887  0.890581   
26     0.693978 -0.195610 -1.296495  1.477459 -1.070322  0.282482  0.002590   
27     0.261885 -0.273123 -1.296495 -1.082964  0.845402  0.822057  0.002590   
28     1.235573 -0.893226 -1.296495  1.477459  0.845402 -1.120412  0.002590   
29    -0.347229 -1.125765  0.771310 -1.082964  0.845402 -1.012497  1.778572   
...         ...       ...       ...       ...       ...       ...       ...   
21570  1.261542  2.207290 -1.296495 -1.082964 -1.070322  1.037887 -0.885401   
21571 -1.026603 -0.738201 -1.296495  0.197247  0.845402 -0.580837  0.002590   
21572 -0.691460  0.269467  0.771310  0.197247 -1.070322  0.929972 -0.885401   
21573  0.862198 -0.350636 -1.296495  0.197247 -1.070322  1.037887  0.002590   
21574  1.136891  0.269467  0.771310  0.197247  0.845402  0.066652  0.002590   
21575  1.079038 -0.893226  0.771310  1.477459  0.845402 -0.041262  0.002590   
21576  0.054856  0.346980  0.771310 -1.082964  0.845402 -0.904582  0.002590   
21577 -1.393485 -0.195610  0.771310  1.477459  0.845402 -0.257092  0.890581   
21578  0.120788 -0.118097  0.771310  0.197247  0.845402 -1.336242  0.002590   
21579  1.003007 -0.738201  0.771310 -1.082964  0.845402 -1.012497  0.002590   
21580  0.322768  2.594855 -1.296495 -1.082964  0.845402  0.606227 -0.885401   
21581 -0.677322 -0.893226 -1.296495  0.197247  2.761125  1.685377  0.002590   
21582 -0.050318 -0.273123  0.771310 -1.082964  0.845402 -0.580837  0.890581   
21583 -1.206653 -0.893226 -1.296495  1.477459  0.845402 -0.580837  0.002590   
21584 -1.398390 -1.048252  0.771310 -1.082964  0.845402 -0.580837  0.890581   
21585 -1.266237 -1.048252  0.771310  0.197247  0.845402 -0.796667 -0.885401   
21586  1.556144 -0.505662  0.771310  1.477459 -1.070322  0.498312  1.778572   
21587  0.740001 -0.660688  0.771310  0.197247  0.845402 -1.228327  1.778572   
21588 -1.150099 -0.815713  0.771310  0.197247  0.845402 -0.

In [73]:
Y = merged_data['Y']

In [74]:
Y

0        1
1        0
2        0
3        1
4        1
5        0
6        1
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       1
19       0
20       1
21       1
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       1
        ..
21570    1
21571    1
21572    0
21573    0
21574    1
21575    0
21576    0
21577    0
21578    0
21579    0
21580    1
21581    0
21582    0
21583    0
21584    0
21585    1
21586    1
21587    1
21588    0
21589    0
21590    0
21591    1
21592    1
21593    0
21594    0
21595    0
21596    0
21597    0
21598    1
21599    0
Name: Y, Length: 21600, dtype: int64

In [75]:
pwd()

'C:\\Users\\ASHISH\\Desktop\\CLASSIFICATION-SUPERVISED LEARNING'

In [76]:
X1 = np.array(merged_data_feature_z)

In [77]:
X1

array([[ 1.47188938,  1.19962219,  0.7713105 , ..., -0.0825983 ,
        -0.06912711, -0.02240264],
       [-1.54554677,  2.36231583, -1.29649473, ..., -0.51436233,
        -0.19988322, -0.34139249],
       [-0.02579194, -1.12576508, -1.29649473, ..., -0.42850834,
        -0.39868183, -0.36243282],
       ...,
       [-0.94205954, -0.19561017, -1.29649473, ...,  0.28114099,
         0.24110852,  0.30233994],
       [-0.74238794,  0.11444147, -1.29649473, ...,  1.23283187,
         1.24923853,  1.55533617],
       [-1.3457309 , -1.04825217,  0.7713105 , ..., -0.67086343,
        -0.66719647, -0.66527693]])

In [78]:
Y1 = np.array(Y)

In [79]:
Y1

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [80]:
data_test = data3.iloc[:,0:16].values

In [81]:
data_test

array([[ 17083,  50000,      2, ...,  44719,  40002,  38008],
       [  3494, 120000,      2, ...,  12200,  11761,   6761],
       [ 21945, 120000,      2, ...,      0,   2382,      0],
       ...,
       [  3598,  50000,      2, ...,  43594,  38222,  13026],
       [ 18841, 190000,      2, ...,   4686,   5459,   6214],
       [ 21365,  70000,      1, ...,  21410,  22437,  23448]], dtype=int64)

In [82]:
data_test_Y = data3['Y']

In [83]:
X_Train = X1
Y_Train = Y1
X_Test = data_test
Y_Test = data_test_Y

In [84]:
X_Train.shape, Y_Train.shape, X_Test.shape, Y_Test.shape

((21600, 16), (21600,), (2399, 16), (2399,))

In [85]:
from sklearn.tree import DecisionTreeClassifier

# Call Decision Tree Classifier algorithm again and predict
DTClassifier_new = DecisionTreeClassifier (max_depth=3, random_state = 0)
DTClassifier_new.fit(X_Train, Y_Train)
predicted_labels = DTClassifier_new.predict(X_Test)
print(predicted_labels)
#accuracy_score_new = accuracy_score(Y_Test, predicted_labels)
#print(accuracy_score_new)

[0 0 0 ... 1 1 0]


In [86]:
from sklearn.tree import DecisionTreeClassifier

# Call Decision Tree Classifier algorithm again and predict
DTClassifier_new = DecisionTreeClassifier (max_depth=20, random_state = 0)
DTClassifier_new.fit(X_Train, Y_Train)
predicted_labels = DTClassifier_new.predict(X_Test)
print(predicted_labels)
#accuracy_score_new = accuracy_score(Y_Test, predicted_labels)
#print(accuracy_score_new)

[0 0 0 ... 0 0 0]


In [87]:
from sklearn.neighbors import KNeighborsClassifier
NNH= KNeighborsClassifier(n_neighbors = 21 )
NNH.fit(X_Train, Y_Train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=21, p=2,
           weights='uniform')

In [88]:
predicted_labels = NNH.predict(X_Test)

In [89]:
NNH= KNeighborsClassifier(n_neighbors = 25 )
NNH.fit(X_Train, Y_Train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=25, p=2,
           weights='uniform')

In [91]:
def getAccuracy(testSet, predictions):
	correct = 0
	for x in range(len(testSet)):
		if testSet[x][-1] is predictions[x]:
			correct += 1
	return (correct/float(len(testSet))) * 100.0

In [92]:
accuracy_score = getAccuracy(Y_Test, predicted_labels)

IndexError: invalid index to scalar variable.

In [ ]:
sub = pd.DataFrame(pd.read_csv("test.csv")['Ref.No'])
sub['Y'] = predicted_labels
sub.to_csv("citibank2_submission.csv", index = False)